name: Run Unit Tests

on:
  push:
    branches:
      - mainline

env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/account-service:test
  LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/account-service:latest

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Run unittests
        run: |
          docker run pytest tests
          docker rm -rf ${{ env.TEST_TAG }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.LATEST_TAG }}
